version: '3.3'
services:
  app:
    build: .
    ports:
      - '9000:9000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/fch
      - NODE_ENV=production

  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - '27017:27017'
